export BASE_MARATHON_URL=http://marathon.mesos:8080
export BASE_METRONOME_URL=http://metronome.mesos:9000

echo BASE_MARATHON_URL=$BASE_MARATHON_URL
echo BASE_METRONOME_URL=$BASE_METRONOME_URL
echo DOCKER_URI=$DOCKER_URI